version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    # ports:
    #   - "3000:80"
    networks:
      - haproxynet
    restart: unless-stopped
  haproxy:
    container_name: haproxy
    build:
      context: ./haproxy/alpine/
    env_file:
        - ./haproxy/alpine/haproxy.env
    image: eu.gcr.io/hyperd-containers/haproxy:latest
    networks:
      - haproxynet
    ports:
      - "8443:443"
      - "5000:4000"
    # volumes:
    #   - ./tls:/etc/tls/certs
    depends_on:
      - nginx
    links:
      - "nginx:nginx"
    restart: unless-stopped
networks:
  haproxynet:
    name: haproxy_network