#+++++++++++++++++++++++++++++++++++++++++++++++++++
# Dockerfile for eu.gcr.io/hyperd-containers/python3
#+++++++++++++++++++++++++++++++++++++++++++++++++++

FROM eu.gcr.io/hyperd-containers/centos:base

COPY conf/ /opt/docker/

RUN set -x \
    && yum-upgrade \
    && yum-install \
        make \
        gcc \
        zlib-devel \
        bzip2-devel \
        openssl-devel \
        ncurses-devel \
        sqlite-devel \
        readline-devel \
        tk-devel \
        gdbm-devel \
        xz-devel \
        libffi-devel \
        python2-devel \
        openldap-devel \
    && curl https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tgz -o Python-3.8.2.tgz \
    && tar xzf Python-3.8.2.tgz \
    && cd Python-3.8.2 \
    && ./configure --enable-optimizations \
    && make altinstall -j6 \
    && cd - \
    && rm -rf Python-3.8.2.tgz Python-3.8.2 \
    && curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python3.8 get-pip.py \
    && rm -rf get-pip.py \
    && pip3 install --upgrade pip==20.0.2 \
    && pip3 install venvctl==1.3.8 psutil==5.7.0 \
    && pip2 install --upgrade pip==20.0.2 \
    && pip2 install virtualenv==20.0.15 \
    && docker-run-bootstrap \
    && docker-image-cleanup


CMD ["python3"]

LABEL org.opencontainers.image.vendor="Hyperd" \
    org.opencontainers.image.url="eu.gcr.io/hyperd-containers/venv-builder" \
    org.opencontainers.image.title="virtual envs builder based on CentoOS Container Image" \
    org.opencontainers.image.description="A virtual envs builder leveraging both Python 3 and Python2" \
    org.opencontainers.image.version="v1.0.0" \
    org.opencontainers.image.documentation="README.md"
